openapi: 3.0.1
info:
  title: ShopQuote API
  version: 1.0.0
  description: Submit a STEP or DXF file and receive a parsed quote with operations and flat dimensions.

servers:
  - url: https://shopquote-api.onrender.com

paths:
  /quote:
    post:
      summary: Generate a quote for a STEP or DXF file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Quoting result
          content:
            application/json:
              schema:
                type: object
                properties:
                  quoted_part:
                    type: string
                  geometry:
                    type: object
                  price:
                    type: string
