openapi: 3.1.0
info:
  title: shopQuote API
  version: 1.0.0
  description: Unfolds sheet metal parts to generate flat patterns and quote pricing.

servers:
  - url: https://shopquote-api.onrender.com

paths:
  /quote:
    post:
      summary: Upload a file to receive quote and flat pattern
      operationId: getQuote
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: A sheet metal file (.step, .dxf, .fcstd)
      responses:
        "200":
          description: Quote with dimensions and DXF string
          content:
            application/json:
              schema:
                type: object
                properties:
                  quote:
                    type: number
                    description: Estimated cost
                  flat_area_mm2:
                    type: number
                    description: Flat pattern area in mm²
                  bounding_box_mm:
                    type: object
                    properties:
                      x:
                        type: number
                      y:
                        type: number
                      z:
                        type: number
                  flat_pattern:
                    type: object
                    properties:
                      flat_x_mm:
                        type: number
                      flat_y_mm:
                        type: number
                  flat_dxf:
                    type: string
                    description: Flattened shape as DXF string
